Repository Clean-Code-Team/Prototype, pull requests merged in 2023-11, with the labels that each got.

#1 feat: score effect update
  src/engine/DrawManager.java
Labels: enhancement

#2 feat: change the ship design
  res/graphics
  src/screen/GameScreen.java
Labels: D+2, 📍 feature

#7 feat : show an effect when the player eat an item
  res/graphics
  src/engine/Cooldown.java
  src/engine/DrawManager.java
  src/entity/Item.java
  src/entity/ItemPool.java
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: D+2, 📍 feature, 🐝 bug

#8 feat: change some feature about `BulletY`
  res/graphics
  src/engine/DrawManager.java
  src/entity/BulletY.java
  src/entity/Ship.java
Labels: D+2, 📍 feature

#9 feat: ghost after-image
  src/engine/DrawManager.java
Labels: D+2, 📍 feature, 🛠️ refactoring

#10 feat: apply a new color algorithm to the title
  src/engine/DrawManager.java
  test/engine/DrawLoadingTest.java
  test/scoreColorTest.java
  test/slowlyChangingColorsTest.java
Labels: D+2, ✅ test, 📍 feature
